# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: cdk
    before: |
      npm i -g aws-cdk
      mkdir hello-cdk
      cd hello-cdk
  - name: terraform
    before: |
      ./bin/terraform_cli_install.sh
  - name: Script Task
    env:
      AWS_CLI_AUTO_PROMPT: on-partial 
    before: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install 
      cd $THEIA_WORKSPACE_ROOT
